[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
;upload_port = /dev/ttyUSB0   ; leave commented to let PlatformIO auto-detect the port
monitor_speed = 115200
lib_ldf_mode = deep

lib_deps =
    tzapu/WiFiManager @ ^2.0.17